"""Framework and runtime identification from exact evidence (04/B, rule 38).

A framework component is emitted only from a version-bearing string, symbol
set or header that is named here; a file name alone is a *hint* property,
never a component. Every detector states its evidence as
``{what, where, value}`` triples so a consumer can audit the identification
against the bytes it came from, and each one was confirmed on the Android
corpus (tier-0 platform libraries, tier-2 F-Droid apps, tier-3 builds) with
the confirming oracle named in the tests. The committed R1 evidence files
(``tests/data/android/<framework>-evidence.json``, generated by
``tests/scripts/android/extract_identification_evidence.py``) carry the
corpus bytes' side of each comparison.

The module is deliberately string-and-symbol keyed and cheap: the strings
come from LIEF's own string iterator (the same source
``binary_common.binary_strings`` feeds ``parse_strings``), the symbol sets
from the metadata buckets ``parse_symbols`` already built, and the note from
``parse_android_facts``. Nothing here disassembles or reads outside the
parsed object.

Version honesty (rules 11/34): a detector that cannot map its evidence to a
published version emits no version rather than guessing.

Output: identification records stored under ``metadata["frameworks"]``::

    {
        "framework": "ndk-libcxx",
        "version": "r26b",
        "evidence": [
            {"what": ".note.android.ident NDK version",
             "where": "notes", "value": "r26b"},
        ],
        "hints": [],
        "static": False,
    }

Absence of the key means the pass never ran (non-ELF); an empty list means
no framework evidence matched — never "no frameworks present".
"""

from __future__ import annotations

import re

import lief

from blint.logger import LOG

# --- The component identity table (tests/scripts/android/
# h0-identification-shape.md section 3 carries the purl justifications).
# ``purl`` is (type, namespace, name); ``replaces`` names the file component
# this framework takes over when the whole .so file is the framework's
# artifact.
FRAMEWORK_COMPONENTS: dict[str, dict] = {
    # The NDK's C++ runtime: no purl ecosystem type exists for NDK
    # components, so the spec's generic fallback with an android-ndk
    # namespace; the version is the NDK release the runtime came from.
    "ndk-libcxx": {
        "purl": ("generic", "android-ndk", "libcxx"),
        "name": "libc++ (NDK)",
        "replaces": "libc++_shared.so",
    },
}

# --- Evidence patterns ------------------------------------------------------
# parse_symbols stores demangled spellings, so the patterns match the
# demangled form (the R1 evidence JSONs record the llvm-nm --demangle
# oracle alongside).
# The NDK C++ runtime itself: it is the only NDK library that exports
# operator new/delete (libc++abi lives in libc++_shared). An ordinary
# NDK-built C++ library imports them.
LIBCXX_OPERATOR_NEW_RE = re.compile(r"^operator new")
# std::__ndk1 (the NDK libc++ inline namespace) - secondary evidence only:
# every NDK-built C++ library carries it, so it cannot pick out the runtime.
NDK1_NAMESPACE_RE = re.compile(r"^std::__ndk1::")


def _declared_soname(parsed_obj) -> str | None:
    """The library's declared DT_SONAME - what the loader registers it as.

    This is ELF structural identity, not a file name: a renamed copy keeps
    its SONAME, and a library that merely bundles libc++ statically keeps
    its own.
    """
    try:
        for entry in parsed_obj.dynamic_entries:
            if entry.tag == lief.ELF.DynamicEntry.TAG.SONAME:
                return entry.name or None
    except (AttributeError, TypeError):
        return None
    return None


def _iter_strings(parsed_obj):
    """The same raw string source parse_strings reads, unevaluated."""
    from blint.lib.binary_common import binary_strings

    try:
        yield from binary_strings(parsed_obj)
    except (AttributeError, TypeError, ValueError) as e:
        LOG.debug(f"framework_ident: string iteration failed: {type(e).__name__}: {e}")


def _symbol_names(metadata: dict) -> list[str]:
    names = []
    for bucket in ("dynamic_symbols", "symtab_symbols"):
        for symbol in metadata.get(bucket) or []:
            if isinstance(symbol, dict) and symbol.get("name"):
                names.append(str(symbol["name"]))
    return names


def _exported_symbol_names(metadata: dict) -> list[str]:
    return [
        str(symbol.get("name"))
        for symbol in metadata.get("dynamic_symbols") or []
        if isinstance(symbol, dict) and symbol.get("name") and symbol.get("is_exported")
    ]


def _record(framework: str, evidence: list[dict], hints: list[str],
            version: str | None = None, static: bool = False) -> dict:
    record = {
        "framework": framework,
        "evidence": evidence,
        "hints": hints,
        "static": static,
    }
    if version:
        record["version"] = version
    return record


def identify_frameworks(parsed_obj, metadata: dict) -> list[dict]:
    """Run every evidence-keyed detector over one parsed ELF."""
    records: list[dict] = []
    symbols = _symbol_names(metadata)
    exported = _exported_symbol_names(metadata)
    has_ndk1_symbols = any(NDK1_NAMESPACE_RE.match(n) for n in symbols)
    exports_operator_new = any(LIBCXX_OPERATOR_NEW_RE.match(n) for n in exported)

    # H1: the NDK C++ runtime. Evidence: the declared DT_SONAME
    # (libc++_shared.so - what the loader registers, not the file name), the
    # .note.android.ident NDK version and build number, the std::__ndk1
    # inline namespace, and the exported operator new/delete that only a
    # C++ runtime defines. The symbol and note evidence alone hold for
    # every NDK-built C++ library, and app libraries that bundle libc++
    # statically also export operator new (frescolib's
    # libnative-imagetranscoder.so does) - it is the declared SONAME that
    # says this file *is* the shared runtime rather than carrying a copy.
    android_ident = (metadata.get("android") or {}).get("android_ident") or {}
    soname = _declared_soname(parsed_obj)
    if (
        (ndk_version := android_ident.get("ndk_version"))
        and soname == "libc++_shared.so"
        and has_ndk1_symbols
        and exports_operator_new
    ):
        evidence = [
            {
                "what": ".note.android.ident NDK version",
                "where": "notes",
                "value": ndk_version,
            }
        ]
        if build_number := android_ident.get("ndk_build_number"):
            evidence.append(
                {
                    "what": ".note.android.ident NDK build number",
                    "where": "notes",
                    "value": build_number,
                }
            )
        if has_ndk1_symbols:
            evidence.append(
                {
                    "what": "std::__ndk1 inline namespace symbols",
                    "where": "symbols",
                    "value": "std::__ndk1::*",
                }
            )
        evidence.append(
            {
                "what": "exported operator new/delete (libc++abi)",
                "where": "symbols",
                "value": "operator new*",
            }
        )
        evidence.append(
            {
                "what": "declared DT_SONAME",
                "where": "dynamic_entries",
                "value": soname,
            }
        )
        records.append(
            _record("ndk-libcxx", evidence, [], version=ndk_version)
        )
    return records


def attach_frameworks(metadata: dict, parsed_obj) -> dict:
    """Wire-up for ``parse()``: store identifications under ``frameworks``."""
    try:
        records = identify_frameworks(parsed_obj, metadata)
    except (AttributeError, TypeError, ValueError) as e:
        LOG.debug(f"Framework identification failed: {type(e).__name__}: {e}")
        return metadata
    if records:
        metadata["frameworks"] = records
    return metadata


def framework_identity(record: dict, abis: list[str]) -> tuple[str, str, str] | None:
    """The (name, version, purl) a framework record's SBOM component carries.

    None when the framework is not in the component table (a hint-only
    identification keeps the generic file component). The ABI qualifier
    rides the purl exactly like the generic file component's did, so
    bom_refs stay deterministic per input.
    """
    entry = FRAMEWORK_COMPONENTS.get(record.get("framework") or "")
    if not entry:
        return None
    purl_type, namespace, name = entry["purl"]
    qualifiers = {"abi": ",".join(sorted(abis))} if abis else {}
    from packageurl import PackageURL

    purl = PackageURL(
        type=purl_type,
        namespace=namespace,
        name=name,
        version=record.get("version") or None,
        qualifiers=qualifiers,
    ).to_string()
    return entry["name"], record.get("version") or "", purl
