"""Framework and runtime identification from exact evidence (04/B, rule 38).

A framework component is emitted only from a version-bearing string, symbol
set or header that is named here; a file name alone is a *hint* property,
never a component. Every detector states its evidence as
``{what, where, value}`` triples so a consumer can audit the identification
against the bytes it came from, and each one was confirmed on the Android
corpus (tier-0 platform libraries, tier-2 F-Droid apps, tier-3 builds) with
the confirming oracle named in the tests. The committed R1 evidence files
(``tests/data/android/<framework>-evidence.json``, generated by
``tests/scripts/android/extract_identification_evidence.py``) carry the
corpus bytes' side of each comparison.

The module is deliberately string-and-symbol keyed and cheap: the strings
come from LIEF's own string iterator (the same source
``binary_common.binary_strings`` feeds ``parse_strings``), the symbol sets
from the metadata buckets ``parse_symbols`` already built, and the note from
``parse_android_facts``. Nothing here disassembles or reads outside the
parsed object.

Version honesty (rules 11/34): a detector that cannot map its evidence to a
published version emits no version rather than guessing.

Output: identification records stored under ``metadata["frameworks"]``::

    {
        "framework": "ndk-libcxx",
        "version": "r26b",
        "evidence": [
            {"what": ".note.android.ident NDK version",
             "where": "notes", "value": "r26b"},
        ],
        "hints": [],
        "static": False,
    }

Absence of the key means the pass never ran (non-ELF); an empty list means
no framework evidence matched — never "no frameworks present".
"""

from __future__ import annotations

import re

import lief

from blint.logger import LOG

# --- The component identity table (tests/scripts/android/
# h0-identification-shape.md section 3 carries the purl justifications).
# ``purl`` is (type, namespace, name); ``replaces`` names the file component
# this framework takes over when the whole .so file is the framework's
# artifact.
FRAMEWORK_COMPONENTS: dict[str, dict] = {
    # The NDK's C++ runtime: no purl ecosystem type exists for NDK
    # components, so the spec's generic fallback with an android-ndk
    # namespace; the version is the NDK release the runtime came from.
    "ndk-libcxx": {
        "purl": ("generic", "android-ndk", "libcxx"),
        "name": "libc++ (NDK)",
        "replaces": "libc++_shared.so",
    },
    # The Flutter engine. Post-2025 the engine source and the revision
    # strings it embeds both live in flutter/flutter (the monorepo), so the
    # spec's github type names the project. No version: the engine's
    # revision strings are reported as hashes because nothing published
    # maps them to releases at scan time.
    "flutter-engine": {
        "purl": ("github", "flutter", "flutter"),
        "name": "flutter_engine",
        "replaces": "libflutter.so",
    },
    # React Native: the release versions are published and consumed on npm,
    # so the spec's npm type carries the exact identity a consumer matches.
    "react-native": {
        "purl": ("npm", None, "react-native"),
        "name": "react-native",
    },
    # fbjni: a separate upstream project with no version-bearing evidence in
    # release builds, so a versionless component from its own evidence.
    "fbjni": {
        "purl": ("github", "facebook", "fbjni"),
        "name": "fbjni",
    },
    # BoringSSL carries no version strings in release builds; the component
    # is versionless from its own symbol/string evidence.
    "boringssl": {
        "purl": ("github", "google", "boringssl"),
        "name": "BoringSSL",
        "replaces": "libcrypto.so",
    },
    "openssl": {
        "purl": ("github", "openssl", "openssl"),
        "name": "OpenSSL",
    },
    # NSS upstream publishes via the nss-dev GitHub mirror
    # (gitlab.mozilla.org is the origin); the mirror is the public
    # reference identity.
    "nss": {
        "purl": ("github", "nss-dev", "nss"),
        "name": "NSS",
    },
    # VLC: libvlc.so is the VLC core; the release string carries the
    # version (the codename form "3.0.23 Vetinari" rides the evidence).
    "vlc": {
        "purl": ("github", "videolan", "vlc"),
        "name": "libvlc",
    },
    # Qt5Core is a qtbase artifact; the github type names the official
    # mirror of code.qt.io's qt/qtbase.
    "qt": {
        "purl": ("github", "qt", "qtbase"),
        "name": "Qt",
    },
}

# Nested-only identifications: statically linked inside a host library,
# they become child components of the host record and never replace it.
NESTED_COMPONENTS: dict[str, dict] = {
    # The Dart VM embedded in the Flutter engine; the version comes from
    # the Dart VM version string the engine prints (its own
    # runtime/vm/version_in.cc template).
    "dart-sdk": {
        "purl": ("github", "dart-lang", "sdk"),
        "name": "Dart SDK",
    },
    # BoringSSL statically linked inside the Flutter engine.
    "boringssl": {
        "purl": ("github", "google", "boringssl"),
        "name": "BoringSSL",
    },
}

# --- Evidence patterns ------------------------------------------------------
# parse_symbols stores demangled spellings, so the patterns match the
# demangled form (the R1 evidence JSONs record the llvm-nm --demangle
# oracle alongside).
# The NDK C++ runtime itself: it is the only NDK library that exports
# operator new/delete (libc++abi lives in libc++_shared). An ordinary
# NDK-built C++ library imports them.
LIBCXX_OPERATOR_NEW_RE = re.compile(r"^operator new")
# std::__ndk1 (the NDK libc++ inline namespace) - secondary evidence only:
# every NDK-built C++ library carries it, so it cannot pick out the runtime.
NDK1_NAMESPACE_RE = re.compile(r"^std::__ndk1::")
# The Dart VM prints its version as
#   3.11.5 (stable) (Wed Apr 15 00:36:32 2026 -0700) on "android_arm64"
# (dart-lang/sdk runtime/vm/version_in.cc: the str_ template).
DART_VM_VERSION_RE = re.compile(
    r"^(?P<version>\d+\.\d+\.\d+(?:\.\d+)?) \((?P<channel>[a-z]+)\) "
    r"\((?P<date>[^)]+)\) on \"(?P<target>[a-z0-9_]+)\"$"
)
# Bare 40-hex revision strings (the whole string is the hash). The Flutter
# engine bakes four of these (shell/version/BUILD.gn: FLUTTER_ENGINE_VERSION,
# FLUTTER_CONTENT_HASH, SKIA_VERSION, DART_VERSION); toolchain revisions
# never appear as bare strings, so no prefix table is needed.
HEX40_RE = re.compile(r"^[0-9a-f]{40}$")
# react-native's own build stamps Hermes with the RN release:
# packages/react-native/ReactAndroid/hermes-engine/build.gradle.kts
# ("-DHERMES_RELEASE_VERSION=for RN ${version}"), compiled in by hermes'
# CMakeLists.txt (-DHERMES_RELEASE_VERSION="..."). A version-bearing
# string is the only RN version evidence accepted (04/B).
RN_RELEASE_RE = re.compile(r"^for RN (?P<version>\d+\.\d+\.\S+)$")
# A Dart snapshot version hash: 32 lower-hex chars (an MD5 - see
# DART_SNAPSHOT_HASH_EVIDENCE below).
DART_SNAPSHOT_HASH_RE = re.compile(r"^[0-9a-f]{32}$")
# Flutter engine's exported InternalFlutterGpu_* API surface.
FLUTTER_SYMBOL_RE = re.compile(r"^InternalFlutterGpu_")
# facebook::jni (github.com/facebook/fbjni) symbols - paired with the
# runtime string below, because header-using libraries instantiate
# facebook::jni templates without being fbjni itself.
FBJNI_SYMBOL_RE = re.compile(r"^facebook::jni::")
# fbjni's own runtime strings: only its translation units define them
# (measured: zero occurrences in libreactnative/libjsi/libappmodules).
FBJNI_RUNTIME_STRING = "fbjni is uninitialized"
# NSS ships its version as "Version: NSS 3.128" and exports
# NSS_VersionCheck; the number is the NSS release version.
NSS_VERSION_RE = re.compile(r"^Version: NSS (?P<version>\d+\.\d+(?:\.\d+)*)$")
# libvlc prints "VLC 3.0.23" (the release; the codename form
# "3.0.23 Vetinari" also appears - libvlc/media.c's VERSION_TEXT).
VLC_VERSION_RE = re.compile(r"^VLC (?P<version>\d+\.\d+\.\d+)$")
# Qt carries QT_VERSION_STR, rendered in libQt5Core strings as
# "Qt 5.15.15 (arm64-little_endian-lp64 shared (dynamic) release build; ...)".
QT_VERSION_RE = re.compile(r"^Qt (?P<version>\d+\.\d+\.\d+) \(")
# BoringSSL's own symbol prefix (BORINGSSL_keccak and friends) - named
# BoringSSL-only evidence for a crypto library carrying no OpenSSL banner.
BORINGSSL_SYMBOL_RE = re.compile(r"^BORINGSSL_")
# BoringSSL's vendored source path, baked into the Flutter engine's
# assertion strings (flutter/third_party/boringssl/src/...): the named
# token for a BoringSSL copy statically linked into a host library.
BORINGSSL_VENDORED_PATH = "third_party/boringssl/"
# OpenSSL's version banner, "OpenSSL 3.0.2 15 Mar 2022"
# (OPENSSL_VERSION_TEXT: version then "DD Mon YYYY").
OPENSSL_BANNER_RE = re.compile(
    r"^OpenSSL (?P<version>\d+\.\d+\.\d+[a-z]*) (?P<date>\d{1,2} [A-Za-z]+ \d{4})$"
)
# Dart AOT snapshot exports (libapp.so shape).
DART_SNAPSHOT_SYMBOL_RE = re.compile(r"^_kDart(Vm|Isolate)Snapshot")
# The Dart AOT snapshot header: magic f5 f5 dc dc, a u64 length, a u64 kind,
# then the version-hash string (runtime/vm/snapshot.h). The hash itself is
# derived by dart-lang/sdk tools/make_version.py MakeSnapshotHashString.
DART_SNAPSHOT_HASH_EVIDENCE = (
    "Dart snapshot version hash "
    "(tools/make_version.py MakeSnapshotHashString)"
)
DART_SNAPSHOT_HASH_OFFSET = 20
DART_SNAPSHOT_HASH_LEN = 32


def _declared_soname(parsed_obj) -> str | None:
    """The library's declared DT_SONAME - what the loader registers it as.

    This is ELF structural identity, not a file name: a renamed copy keeps
    its SONAME, and a library that merely bundles libc++ statically keeps
    its own.
    """
    try:
        for entry in parsed_obj.dynamic_entries:
            if entry.tag == lief.ELF.DynamicEntry.TAG.SONAME:
                return entry.name or None
    except (AttributeError, TypeError):
        return None
    return None


def _iter_strings(parsed_obj):
    """The same raw string source parse_strings reads, unevaluated."""
    from blint.lib.binary_common import binary_strings

    try:
        yield from binary_strings(parsed_obj)
    except (AttributeError, TypeError, ValueError) as e:
        LOG.debug(f"framework_ident: string iteration failed: {type(e).__name__}: {e}")


def _symbol_names(metadata: dict) -> list[str]:
    names = []
    for bucket in ("dynamic_symbols", "symtab_symbols"):
        for symbol in metadata.get(bucket) or []:
            if isinstance(symbol, dict) and symbol.get("name"):
                names.append(str(symbol["name"]))
    return names


def _exported_symbol_names(metadata: dict) -> list[str]:
    return [
        str(symbol.get("name"))
        for symbol in metadata.get("dynamic_symbols") or []
        if isinstance(symbol, dict) and symbol.get("name") and symbol.get("is_exported")
    ]


def _record(framework: str, evidence: list[dict], hints: list[str],
            version: str | None = None, static: bool = False,
            nested: list[dict] | None = None) -> dict:
    record = {
        "framework": framework,
        "evidence": evidence,
        "hints": hints,
        "static": static,
    }
    if version:
        record["version"] = version
    if nested:
        record["nested"] = nested
    return record


def _react_native_and_fbjni_records(strings_seen: dict, symbols: list[str]) -> list[dict]:
    """H3: React Native from its Hermes build stamp; fbjni on its own evidence.

    React Native's version comes only from the version-bearing string RN's
    build stamps into libhermes.so. fbjni needs BOTH the facebook::jni
    symbol namespace and its own runtime string: header-using libraries
    (libreactnative) instantiate the templates, but only fbjni's own
    translation units define the runtime strings.
    """
    records: list[dict] = []
    if (rn := strings_seen.get("rn_release")):
        match, text = rn
        records.append(
            _record(
                "react-native",
                [
                    {
                        "what": "HERMES_RELEASE_VERSION string",
                        "where": "strings",
                        "value": text,
                    }
                ],
                [],
                version=match.group("version"),
            )
        )
    has_fbjni_symbols = any(FBJNI_SYMBOL_RE.match(n) for n in symbols)
    fbjni_string = strings_seen.get("fbjni_runtime_string")
    if has_fbjni_symbols and fbjni_string:
        evidence = [
            {
                "what": "fbjni runtime string",
                "where": "strings",
                "value": fbjni_string,
            },
            {
                "what": "facebook::jni symbol namespace",
                "where": "symbols",
                "value": "facebook::jni::*",
            },
        ]
        records.append(_record("fbjni", evidence, []))
    return records


def _tls_records(strings_seen: dict, symbols: list[str],
                 exported: list[str] | None = None,
                 flutter_hosted: bool = False) -> list[dict]:
    """H4: OpenSSL by its banner; NSS by NSS_VersionCheck plus the version
    string; BoringSSL by the absence of the OpenSSL banner plus
    BoringSSL-only evidence.

    Replace-grade BoringSSL (the file IS the provider, the platform's
    libcrypto.so) requires the BORINGSSL_* EXPORTED symbol prefix - a
    library that merely bundles BoringSSL statically keeps hidden visibility
    and leaks only vendored-path strings (libjingle_peerconnection_so.so:
    0 BORINGSSL_ exports against the platform's 6+). A string-only hit is
    therefore a hint-only record: it never replaces the host's identity.
    A BoringSSL bundled inside the Flutter engine never reaches here - the
    flutter detector nests it.
    """
    records: list[dict] = []
    openssl = strings_seen.get("openssl_banner")
    if openssl:
        match, text = openssl
        records.append(
            _record(
                "openssl",
                [
                    {
                        "what": "OPENSSL_VERSION_TEXT banner",
                        "where": "strings",
                        "value": text,
                    }
                ],
                [],
                version=match.group("version"),
            )
        )
    nss = strings_seen.get("nss_version")
    has_nss_check = any(n == "NSS_VersionCheck" for n in symbols)
    if has_nss_check and nss:
        match, text = nss
        records.append(
            _record(
                "nss",
                [
                    {
                        "what": "NSS_VersionCheck export",
                        "where": "symbols",
                        "value": "NSS_VersionCheck",
                    },
                    {
                        "what": "NSS version string",
                        "where": "strings",
                        "value": text,
                    },
                ],
                [],
                version=match.group("version"),
            )
        )
    if not openssl and not flutter_hosted:
        boringssl_evidence = []
        exports_boringssl = any(
            BORINGSSL_SYMBOL_RE.match(n) for n in (exported or [])
        )
        if exports_boringssl:
            boringssl_evidence.append(
                {
                    "what": "BORINGSSL_* exported symbol prefix",
                    "where": "symbols",
                    "value": "BORINGSSL_*",
                }
            )
        if strings_seen.get("boringssl_string"):
            boringssl_evidence.append(
                {
                    "what": "vendored BoringSSL source path string",
                    "where": "strings",
                    "value": strings_seen["boringssl_string"][:120],
                }
            )
        if boringssl_evidence:
            record = _record("boringssl", boringssl_evidence, [])
            # Without the exported provider surface the file is a host
            # carrying a static copy, not the provider itself.
            record["hint_only"] = not exports_boringssl
            records.append(record)
    return records


def _application_runtime_records(strings_seen: dict) -> list[dict]:
    """H5: application runtimes present in the corpus - VLC and Qt5.

    Unity/IL2CPP and Mono/.NET stay out of scope: the corpus has neither
    (H0 doc), so there are no detectors to write against.
    """
    records: list[dict] = []
    if (vlc := strings_seen.get("vlc_version")):
        match, text = vlc
        records.append(
            _record(
                "vlc",
                [
                    {
                        "what": "VLC release string",
                        "where": "strings",
                        "value": text,
                    }
                ],
                [],
                version=match.group("version"),
            )
        )
    if (qt := strings_seen.get("qt_version")):
        match, text = qt
        records.append(
            _record(
                "qt",
                [
                    {
                        "what": "QT_VERSION_STR string",
                        "where": "strings",
                        "value": text,
                    }
                ],
                [],
                version=match.group("version"),
            )
        )
    return records


def _scan_evidence_strings(parsed_obj) -> dict:
    """One pass over the raw strings, recording each named evidence match.

    Only the first occurrence of each kind is kept - the evidence is the
    presence and content of a version-bearing string, not a census.
    """
    strings_seen: dict = {
        "dart_vm_version": None,
        "hex40": set(),
        "rn_release": None,
        "fbjni_runtime_string": None,
        "nss_version": None,
        "openssl_banner": None,
        "boringssl_string": None,
        "vlc_version": None,
        "qt_version": None,
    }
    for raw in _iter_strings(parsed_obj):
        if not isinstance(raw, str):
            continue
        stripped = raw.strip()
        if not stripped:
            continue
        if strings_seen["dart_vm_version"] is None:
            if match := DART_VM_VERSION_RE.match(stripped):
                strings_seen["dart_vm_version"] = (match, stripped)
        if strings_seen["rn_release"] is None:
            if match := RN_RELEASE_RE.match(stripped):
                strings_seen["rn_release"] = (match, stripped)
        if strings_seen["fbjni_runtime_string"] is None:
            if FBJNI_RUNTIME_STRING in stripped:
                strings_seen["fbjni_runtime_string"] = stripped
        if strings_seen["nss_version"] is None:
            if match := NSS_VERSION_RE.match(stripped):
                strings_seen["nss_version"] = (match, stripped)
        if strings_seen["openssl_banner"] is None:
            if match := OPENSSL_BANNER_RE.match(stripped):
                strings_seen["openssl_banner"] = (match, stripped)
        if strings_seen["boringssl_string"] is None and (
            stripped.lower() == "boringssl" or BORINGSSL_VENDORED_PATH in stripped
        ):
            strings_seen["boringssl_string"] = stripped
        if strings_seen["vlc_version"] is None:
            if match := VLC_VERSION_RE.match(stripped):
                strings_seen["vlc_version"] = (match, stripped)
        if strings_seen["qt_version"] is None:
            if match := QT_VERSION_RE.match(stripped):
                strings_seen["qt_version"] = (match, stripped)
        if HEX40_RE.match(stripped):
            strings_seen["hex40"].add(stripped)
    return strings_seen


def identify_frameworks(parsed_obj, metadata: dict) -> list[dict]:
    """Run every evidence-keyed detector over one parsed ELF."""
    records: list[dict] = []
    symbols = _symbol_names(metadata)
    exported = _exported_symbol_names(metadata)
    has_ndk1_symbols = any(NDK1_NAMESPACE_RE.match(n) for n in symbols)
    exports_operator_new = any(LIBCXX_OPERATOR_NEW_RE.match(n) for n in exported)

    # H1: the NDK C++ runtime. Evidence: the declared DT_SONAME
    # (libc++_shared.so - what the loader registers, not the file name), the
    # .note.android.ident NDK version and build number, the std::__ndk1
    # inline namespace, and the exported operator new/delete that only a
    # C++ runtime defines. The symbol and note evidence alone hold for
    # every NDK-built C++ library, and app libraries that bundle libc++
    # statically also export operator new (frescolib's
    # libnative-imagetranscoder.so does) - it is the declared SONAME that
    # says this file *is* the shared runtime rather than carrying a copy.
    strings_seen = _scan_evidence_strings(parsed_obj)
    records.extend(
        _flutter_and_dart_records(parsed_obj, strings_seen, symbols, metadata)
    )
    records.extend(_react_native_and_fbjni_records(strings_seen, symbols))
    # The Flutter host nests its own BoringSSL; the standalone detector
    # only speaks for libraries that ARE the crypto provider.
    records.extend(
        _tls_records(strings_seen, symbols, exported,
                     flutter_hosted=any(r["framework"] == "flutter-engine" for r in records))
    )
    records.extend(_application_runtime_records(strings_seen))

    android_ident = (metadata.get("android") or {}).get("android_ident") or {}
    soname = _declared_soname(parsed_obj)
    if (
        (ndk_version := android_ident.get("ndk_version"))
        and soname == "libc++_shared.so"
        and has_ndk1_symbols
        and exports_operator_new
    ):
        evidence = [
            {
                "what": ".note.android.ident NDK version",
                "where": "notes",
                "value": ndk_version,
            }
        ]
        if build_number := android_ident.get("ndk_build_number"):
            evidence.append(
                {
                    "what": ".note.android.ident NDK build number",
                    "where": "notes",
                    "value": build_number,
                }
            )
        if has_ndk1_symbols:
            evidence.append(
                {
                    "what": "std::__ndk1 inline namespace symbols",
                    "where": "symbols",
                    "value": "std::__ndk1::*",
                }
            )
        evidence.append(
            {
                "what": "exported operator new/delete (libc++abi)",
                "where": "symbols",
                "value": "operator new*",
            }
        )
        evidence.append(
            {
                "what": "declared DT_SONAME",
                "where": "dynamic_entries",
                "value": soname,
            }
        )
        records.append(
            _record("ndk-libcxx", evidence, [], version=ndk_version)
        )
    return records


def _flutter_and_dart_records(parsed_obj, strings_seen, symbols, metadata) -> list[dict]:
    """H2: the Flutter engine, the Dart VM inside it, and Dart AOT snapshots.

    The engine is identified by its exported InternalFlutterGpu_* surface
    together with an embedded Dart VM version string or a bare revision
    hash. The Dart version string versions a nested dart-sdk record; the
    bare hashes are reported as hashes only. A library exporting the Dart
    AOT snapshot symbols without the engine surface (libapp.so) is a
    hint-only record: the snapshot version hash is reported, never mapped
    to a Dart version (no published table).
    """
    records: list[dict] = []
    has_flutter_symbols = any(FLUTTER_SYMBOL_RE.match(n) for n in symbols)
    has_dart_snapshot_symbols = any(DART_SNAPSHOT_SYMBOL_RE.match(n) for n in symbols)
    dart_match = strings_seen.get("dart_vm_version")
    hex40 = strings_seen.get("hex40") or set()

    if has_flutter_symbols and (dart_match or hex40):
        evidence = [
            {
                "what": "InternalFlutterGpu_* exported symbols",
                "where": "symbols",
                "value": "InternalFlutterGpu_*",
            }
        ]
        nested: list[dict] = []
        if dart_match:
            match, text = dart_match
            evidence.append(
                {
                    "what": "Dart VM version string",
                    "where": "strings",
                    "value": text,
                }
            )
            nested.append(
                _record(
                    "dart-sdk",
                    [
                        {
                            "what": "Dart VM version string",
                            "where": "strings",
                            "value": text,
                        }
                    ],
                    [],
                    version=match.group("version"),
                    static=True,
                )
            )
        if hex40:
            evidence.append(
                {
                    "what": "bare 40-hex revision strings (FLUTTER_ENGINE_VERSION / "
                            "FLUTTER_CONTENT_HASH / SKIA_VERSION / DART_VERSION slots, "
                            "shell/version/BUILD.gn)",
                    "where": "strings",
                    "value": ", ".join(sorted(hex40)),
                }
            )
        if strings_seen.get("boringssl_string"):
            # The engine bundles BoringSSL statically: a nested
            # identification, never a second copy of the host.
            nested.append(
                _record(
                    "boringssl",
                    [
                        {
                            "what": "vendored BoringSSL source path (statically linked)",
                            "where": "strings",
                            "value": BORINGSSL_VENDORED_PATH,
                        }
                    ],
                    [],
                    static=True,
                )
            )
        records.append(
            _record("flutter-engine", evidence, [], nested=nested or None)
        )

    if has_dart_snapshot_symbols and not has_flutter_symbols:
        evidence = [
            {
                "what": "Dart AOT snapshot symbols",
                "where": "symbols",
                "value": "_kDart*Snapshot*",
            }
        ]
        if snapshot_hash := _dart_snapshot_hash(parsed_obj, metadata):
            evidence.append(
                {
                    "what": DART_SNAPSHOT_HASH_EVIDENCE,
                    "where": "bytes at _kDartIsolateSnapshotData+20",
                    "value": snapshot_hash,
                }
            )
        records.append(_record("dart-aot-snapshot", evidence, []))
    return records


def _dart_snapshot_hash(parsed_obj, metadata) -> str | None:
    """The 32-hex snapshot version hash from the snapshot data's header.

    Read at the documented header offset; anything unexpected (a short
    read, a non-hex payload) yields None rather than a guess.
    """
    address = None
    for symbol in metadata.get("dynamic_symbols") or []:
        if isinstance(symbol, dict) and symbol.get("name") in (
            "_kDartIsolateSnapshotData",
            "_kDartVmSnapshotData",
        ):
            raw = symbol.get("address") or symbol.get("value")
            try:
                address = int(str(raw), 16)
                break
            except (TypeError, ValueError):
                continue
    if address is None:
        return None
    try:
        content = parsed_obj.get_content_from_virtual_address(
            address + DART_SNAPSHOT_HASH_OFFSET, DART_SNAPSHOT_HASH_LEN
        )
        text = bytes(content).decode("ascii", errors="ignore")
    except (AttributeError, TypeError, ValueError):
        return None
    if DART_SNAPSHOT_HASH_RE.match(text):
        return text
    return None


def attach_frameworks(metadata: dict, parsed_obj) -> dict:
    """Wire-up for ``parse()``: store identifications under ``frameworks``."""
    try:
        records = identify_frameworks(parsed_obj, metadata)
    except (AttributeError, TypeError, ValueError) as e:
        LOG.debug(f"Framework identification failed: {type(e).__name__}: {e}")
        return metadata
    if records:
        metadata["frameworks"] = records
    return metadata


def framework_identity(record: dict, abis: list[str]) -> tuple[str, str, str] | None:
    """The (name, version, purl) a framework record's SBOM component carries.

    None when the framework is not in the component table, or when the
    record is hint-only (a framework detected inside a file that keeps its
    own identity - such a record never replaces the host). The ABI
    qualifier rides the purl exactly like the generic file component's did,
    so bom_refs stay deterministic per input.
    """
    if record.get("hint_only"):
        return None
    entry = FRAMEWORK_COMPONENTS.get(record.get("framework") or "")
    if not entry:
        return None
    purl_type, namespace, name = entry["purl"]
    qualifiers = {"abi": ",".join(sorted(abis))} if abis else {}
    from packageurl import PackageURL

    purl = PackageURL(
        type=purl_type,
        namespace=namespace,
        name=name,
        version=record.get("version") or None,
        qualifiers=qualifiers,
    ).to_string()
    return entry["name"], record.get("version") or "", purl
